name: "Build and restart bot"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  tests:
    name: tests
    uses: ./.github/workflows/tests.yaml

  push:
    name: push
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set github envirnment variable
        run: echo "VERSION_NUMBER=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: setup docker
        uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build
        run: |
          docker build . --file Dockerfile --tag pgolbus2/cs411-birthday-bot:${{ env.VERSION_NUMBER }}
      - name: push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cs411-birthday-bot:${{ env.VERSION_NUMBER }}

  deploy:
    name: deploy
    needs: push
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set github envirnment variable
        run: echo "VERSION_NUMBER=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login
            docker pull pgolbus2/cs411-birthday-bot:${{ env.VERSION_NUMBER }}
            docker stop birthday-bot || true
            docker rm birthday-bot || true
            docker run -d --name birthday-bot --env "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" --rm -it pgolbus2/cs411-birthday-bot:${{ env.VERSION_NUMBER }}