name: "Deploy to docker hub"

on: 
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  tests:
    name: tests
    uses: ./.github/workflows/tests.yaml

  deploy:
    runs-on: ubuntu-latest
    name: deploy
    needs: [tests]
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}