name: "Build and restart bot"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  tests:
    name: tests
    uses: ./.github/workflows/tests.yaml

  push:
    name: push
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup docker
        uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: get version number
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: build
        run: docker build . --file Dockerfile --tag pgolbus2/cs411-birthday-bot:${{ env.RELEASE_VERSION }}
      - name: push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cs411-birthday-bot:${{ env.RELEASE_VERSION }}

  deploy:
    name: deploy
    needs: push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/cs411-birthday-bot:${{ env.RELEASE_VERSION }}
            docker stop birthday-bot || true
            docker rm birthday-bot || true
            docker run -d --name birthday-bot ${{ secrets.DOCKER_USERNAME }}/cs411-birthday-bot:${{ env.RELEASE_VERSION }}