name: "Build and restart bot"

on: push
#  push:
#    tags:
#      - 'v*.*.*'

jobs:
  # tests:
  #   name: tests
  #   uses: ./.github/workflows/tests.yaml

  version:
    name: version
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get version number
        run: echo "${GITHUB_REF#refs/*/}" > version.txt
      - name: Upload version file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: version-file
          path: version.txt


  # push:
  #   name: push
  #   needs: version
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3
  #     - name: setup docker
  #       uses: docker/setup-buildx-action@v2
  #     - name: login
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Download version file
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: version-file
  #     - name: build
  #       run: |
  #         docker build . --file Dockerfile --tag pgolbus2/cs411-birthday-bot:$(cat version.txt)
  #     - name: push
  #       run: docker push ${{ secrets.DOCKER_USERNAME }}/cs411-birthday-bot:$(cat version.txt)

  deploy:
    name: deploy
    needs: version #push
    runs-on: ubuntu-latest

    steps:
      - name: Download version file
        uses: actions/download-artifact@v2
        with:
          name: version-file

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Read version from file
        run: RELEASE_VERSION=$(cat version.txt)

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/cs411-birthday-bot:${RELEASE_VERSION}
            docker stop birthday-bot || true
            docker rm birthday-bot || true
            docker run -d --name birthday-bot ${{ secrets.DOCKER_USERNAME }}/cs411-birthday-bot:${RELEASE_VERSION}
          EOF
