name: "Build and restart bot"

on: 
  push:
    branches:
      - no_docker

jobs:
  tests:
    name: tests
    uses: ./.github/workflows/tests.yaml

  deploy:
    name: deploy
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            screen -r -d birthday-bot
            PID=$!
            kill $PID
            rm -rf .venvs/birthday-bot/
            python -m venv .venvs/birthday-bot
            source .venvs/birthday-bot/bin/activate
            cd birthday-bot
            git pull
            git checkout no_docker
            git rebase main
            pip install -U pip
            pip install -r requirements.lock
            python bot.py&