name: "Deploy to docker hub"

on: 

  push:
    tags:
      - 'v*.*.*'

jobs:
  tests:
    name: tests
    uses: ./.github/workflows/tests.yaml

  deploy:
    runs-on: ubuntu-latest
    name: deploy
    needs: [tests]
    steps:
      - uses: actions/checkout@v2
      - name: login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: get version number
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: build
        run: docker build . --file Dockerfile --tag pgolbus2/cs411-birthday-bot:${{ env.RELEASE_VERSION }}
      - name: push
        run: docker push ${{secrets.DOCKER_USERNAME}}/cs411-birthday-bot