name: "Run tests on push"

on: [workflow_call, push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.10.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upgrade pip and Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.lock --verbose

      - name: Lint
        run: black --check .
      - name: Unit tests
        run: pytest .